services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork
    env_file:
      - .env

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    env_file:
      - .env
    command: postgres -c listen_addresses=*

networks:
  mynetwork:

volumes:
  postgres_data:
