"""Remove currency column

Revision ID: 59fc08bfffaa
Revises: 589b7ccce624
Create Date: 2025-04-01 11:15:04.795924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59fc08bfffaa'
down_revision: Union[str, None] = '589b7ccce624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
