"""Make exchange nullable

Revision ID: f652cd54ca6d
Revises: 1e8eaa8dcbc2
Create Date: 2025-04-01 06:15:33.548145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f652cd54ca6d'
down_revision: Union[str, None] = '1e8eaa8dcbc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('market_data', 'exchange',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('positions', 'exchange',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'exchange',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('market_data', 'exchange',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
